INSERT INTO box.locations (id, name, description, address) VALUES (1, 'Gabcube', 'Inverse asynchronous budgetary management', '4070 Kensington Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (2, 'Yozio', 'Future-proofed motivating projection', '11258 Gerald Road');
INSERT INTO box.locations (id, name, description, address) VALUES (3, 'Eayo', 'Seamless dynamic forecast', '83920 Huxley Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (4, 'Feedbug', 'Multi-layered hybrid array', '2777 Troy Center');
INSERT INTO box.locations (id, name, description, address) VALUES (5, 'Gabspot', 'Realigned attitude-oriented support', '32009 Mallard Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (6, 'Jatri', 'Phased bottom-line structure', '049 David Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (7, 'Trupe', 'Progressive secondary instruction set', '10 Carpenter Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (8, 'Kimia', 'Ameliorated executive moderator', '577 Mallard Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (9, 'Mudo', 'Synergized global productivity', '502 Sutherland Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (10, 'Kwimbee', 'Centralized needs-based monitoring', '44 Clyde Gallagher Center');
INSERT INTO box.locations (id, name, description, address) VALUES (11, 'Zoomzone', 'Diverse system-worthy collaboration', '1266 Anhalt Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (12, 'Livepath', 'Versatile global process improvement', '92121 Sullivan Center');
INSERT INTO box.locations (id, name, description, address) VALUES (13, 'Oba', 'Mandatory bi-directional middleware', '1162 Brickson Park Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (14, 'Trunyx', 'Operative high-level superstructure', '632 Buell Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (15, 'Gigashots', 'Advanced context-sensitive solution', '2250 Westerfield Way');
INSERT INTO box.locations (id, name, description, address) VALUES (16, 'Rooxo', 'Ergonomic contextually-based website', '079 Dawn Court');
INSERT INTO box.locations (id, name, description, address) VALUES (17, 'Blogtags', 'Phased stable projection', '6060 Bay Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (18, 'Flashdog', 'Public-key human-resource toolset', '39 Claremont Road');
INSERT INTO box.locations (id, name, description, address) VALUES (19, 'Wikido', 'Multi-layered high-level encoding', '22114 Washington Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (20, 'InnoZ', 'Assimilated responsive application', '8 Starling Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (21, 'Linkbridge', 'Grass-roots background website', '51 Eagan Center');
INSERT INTO box.locations (id, name, description, address) VALUES (22, 'Tazzy', 'Robust encompassing functionalities', '58978 Schmedeman Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (23, 'Tagtune', 'Multi-tiered fresh-thinking collaboration', '667 Acker Center');
INSERT INTO box.locations (id, name, description, address) VALUES (24, 'Fivespan', 'Synergized logistical system engine', '270 Arizona Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (25, 'Dabtype', 'Triple-buffered even-keeled archive', '47065 Fordem Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (26, 'Dynazzy', 'Grass-roots intangible flexibility', '2895 Packers Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (27, 'Twiyo', 'Public-key foreground utilisation', '5 Anthes Center');
INSERT INTO box.locations (id, name, description, address) VALUES (28, 'Plambee', 'Switchable needs-based service-desk', '7065 Sage Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (29, 'Demizz', 'Public-key system-worthy solution', '40769 Homewood Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (30, 'Mybuzz', 'Decentralized zero tolerance access', '44075 Ohio Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (31, 'Oba', 'Compatible 24 hour contingency', '3 4th Center');
INSERT INTO box.locations (id, name, description, address) VALUES (32, 'Youbridge', 'Balanced asymmetric conglomeration', '779 Butternut Road');
INSERT INTO box.locations (id, name, description, address) VALUES (33, 'Jaxnation', 'Focused regional concept', '39524 Trailsway Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (34, 'Meetz', 'User-centric needs-based adapter', '9444 Lillian Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (35, 'Camimbo', 'Innovative attitude-oriented encoding', '69 Village Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (36, 'Tanoodle', 'Automated mobile hardware', '5724 New Castle Court');
INSERT INTO box.locations (id, name, description, address) VALUES (37, 'Linktype', 'Face to face radical hub', '021 Texas Road');
INSERT INTO box.locations (id, name, description, address) VALUES (38, 'Blogpad', 'Programmable user-facing knowledge user', '72227 Hallows Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (39, 'Livetube', 'Compatible national algorithm', '0396 Cordelia Road');
INSERT INTO box.locations (id, name, description, address) VALUES (40, 'Rhybox', 'Function-based encompassing matrices', '223 Express Street');
INSERT INTO box.locations (id, name, description, address) VALUES (41, 'Topiclounge', 'Customer-focused logistical capacity', '41712 Eggendart Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (42, 'Edgepulse', 'Synchronised directional parallelism', '02258 Ludington Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (43, 'Wordify', 'Pre-emptive multi-tasking contingency', '990 Valley Edge Place');
INSERT INTO box.locations (id, name, description, address) VALUES (44, 'Skimia', 'Digitized content-based projection', '71 Holy Cross Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (45, 'Kwilith', 'Profound disintermediate info-mediaries', '00563 Clove Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (46, 'Vinder', 'Devolved 4th generation superstructure', '3386 Oneill Point');
INSERT INTO box.locations (id, name, description, address) VALUES (47, 'Dabshots', 'Profit-focused system-worthy portal', '0433 Arkansas Street');
INSERT INTO box.locations (id, name, description, address) VALUES (48, 'Eire', 'Pre-emptive multi-tasking emulation', '1 Daystar Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (49, 'Devpoint', 'Sharable content-based portal', '57209 Clyde Gallagher Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (50, 'Tagfeed', 'Upgradable client-server monitoring', '59774 Rusk Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (51, 'Dabtype', 'Seamless transitional access', '122 Hooker Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (52, 'Meemm', 'Total cohesive local area network', '3149 Hagan Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (53, 'Feedmix', 'Organized multimedia artificial intelligence', '91734 Reinke Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (54, 'Shufflester', 'Innovative global groupware', '0 Sycamore Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (55, 'Muxo', 'Mandatory analyzing policy', '92 Killdeer Center');
INSERT INTO box.locations (id, name, description, address) VALUES (56, 'Linkbuzz', 'Grass-roots foreground standardization', '83 Kings Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (57, 'Abatz', 'Phased solution-oriented hierarchy', '21 Lawn Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (58, 'Skipfire', 'Seamless optimal help-desk', '397 Alpine Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (59, 'Skivee', 'De-engineered regional Graphic Interface', '82 Bluejay Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (60, 'Meemm', 'Compatible composite hub', '62 Canary Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (61, 'Kamba', 'Function-based multimedia productivity', '2404 Sugar Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (62, 'Browsezoom', 'Right-sized value-added infrastructure', '6638 Atwood Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (63, 'Feednation', 'Optimized responsive protocol', '0824 Kings Road');
INSERT INTO box.locations (id, name, description, address) VALUES (64, 'Ooba', 'Upgradable client-server software', '315 Union Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (65, 'Rhynyx', 'Persevering real-time process improvement', '68597 Melrose Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (66, 'Ntags', 'Virtual asymmetric adapter', '19 Charing Cross Way');
INSERT INTO box.locations (id, name, description, address) VALUES (67, 'Youspan', 'Virtual 3rd generation methodology', '17056 Ilene Point');
INSERT INTO box.locations (id, name, description, address) VALUES (68, 'Blogpad', 'Customizable eco-centric encryption', '566 Hanover Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (69, 'Aimbo', 'Profound 5th generation pricing structure', '792 Oak Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (70, 'Babbleset', 'Fundamental solution-oriented installation', '91 Debra Way');
INSERT INTO box.locations (id, name, description, address) VALUES (71, 'Fivespan', 'Re-engineered national portal', '7 Arapahoe Center');
INSERT INTO box.locations (id, name, description, address) VALUES (72, 'Dabfeed', 'Persevering local strategy', '37 Gateway Street');
INSERT INTO box.locations (id, name, description, address) VALUES (73, 'Gabcube', 'Face to face asynchronous solution', '23770 Del Mar Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (74, 'Ntag', 'Proactive logistical protocol', '59504 Evergreen Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (75, 'Youspan', 'Universal responsive parallelism', '5 Quincy Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (76, 'Fiveclub', 'Progressive modular hierarchy', '4405 Prairieview Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (77, 'Yacero', 'Reactive foreground productivity', '6 Hazelcrest Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (78, 'Photospace', 'Progressive holistic policy', '42440 Goodland Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (79, 'Ntag', 'Cross-platform full-range website', '40950 Dennis Park');
INSERT INTO box.locations (id, name, description, address) VALUES (80, 'Wikizz', 'Function-based dedicated encoding', '1287 Fordem Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (81, 'Realmix', 'Synchronised disintermediate internet solution', '9 Hansons Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (82, 'Demivee', 'Operative bi-directional time-frame', '4 Carberry Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (83, 'Innotype', 'Compatible system-worthy artificial intelligence', '90198 Union Court');
INSERT INTO box.locations (id, name, description, address) VALUES (84, 'Teklist', 'Pre-emptive systematic circuit', '3493 Crest Line Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (85, 'Ooba', 'Optimized explicit budgetary management', '76742 Rigney Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (86, 'Shuffledrive', 'Focused system-worthy initiative', '85 Londonderry Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (87, 'Bubbletube', 'Universal executive info-mediaries', '980 Hovde Street');
INSERT INTO box.locations (id, name, description, address) VALUES (88, 'Dazzlesphere', 'Optimized optimizing hierarchy', '10060 Eastwood Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (89, 'Vitz', 'Versatile upward-trending groupware', '52 Prairie Rose Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (90, 'Jamia', 'Assimilated demand-driven website', '87 Meadow Valley Point');
INSERT INTO box.locations (id, name, description, address) VALUES (91, 'Livetube', 'De-engineered grid-enabled monitoring', '05 Springview Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (92, 'Skippad', 'Realigned asynchronous customer loyalty', '76127 Chinook Court');
INSERT INTO box.locations (id, name, description, address) VALUES (93, 'Buzzshare', 'Ergonomic global Graphical User Interface', '6359 Cordelia Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (94, 'Yoveo', 'Synergized global policy', '2787 Bartelt Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (95, 'Edgewire', 'Digitized directional service-desk', '801 Oak Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (96, 'Kanoodle', 'Function-based even-keeled initiative', '96 Lake View Park');
INSERT INTO box.locations (id, name, description, address) VALUES (97, 'Quimm', 'Integrated transitional hardware', '4 Coleman Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (98, 'Meevee', 'Extended discrete application', '49641 Rowland Way');
INSERT INTO box.locations (id, name, description, address) VALUES (99, 'Shufflester', 'Re-engineered attitude-oriented projection', '63371 Helena Court');
INSERT INTO box.locations (id, name, description, address) VALUES (100, 'Devpoint', 'Up-sized demand-driven project', '2 Ramsey Court');
INSERT INTO box.locations (id, name, description, address) VALUES (101, 'Skipstorm', 'Digitized optimizing instruction set', '27837 Miller Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (102, 'Roomm', 'Inverse web-enabled migration', '83 Schlimgen Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (103, 'Feedmix', 'Decentralized 3rd generation ability', '53 Sloan Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (104, 'Mynte', 'Future-proofed actuating system engine', '695 Main Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (105, 'Mudo', 'Distributed user-facing approach', '14 Mallard Way');
INSERT INTO box.locations (id, name, description, address) VALUES (106, 'Tazzy', 'Assimilated responsive flexibility', '6 Independence Court');
INSERT INTO box.locations (id, name, description, address) VALUES (107, 'Twitterworks', 'Public-key tertiary moderator', '71 Darwin Way');
INSERT INTO box.locations (id, name, description, address) VALUES (108, 'Rhynoodle', 'Adaptive heuristic parallelism', '92207 West Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (109, 'Brainverse', 'Managed optimal synergy', '61204 Grim Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (110, 'Fivespan', 'Multi-tiered intangible matrices', '89944 Kingsford Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (111, 'Skalith', 'Multi-lateral dynamic frame', '99 Fulton Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (112, 'Buzzshare', 'Networked grid-enabled hub', '41306 Barnett Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (113, 'Photojam', 'Stand-alone optimal monitoring', '92582 Raven Road');
INSERT INTO box.locations (id, name, description, address) VALUES (114, 'Skimia', 'Re-contextualized asymmetric solution', '85391 Sycamore Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (115, 'Tagcat', 'Balanced regional migration', '2 Little Fleur Park');
INSERT INTO box.locations (id, name, description, address) VALUES (116, 'Bubblemix', 'Public-key neutral core', '929 Vera Road');
INSERT INTO box.locations (id, name, description, address) VALUES (117, 'Skyndu', 'Polarised exuding matrices', '3411 Hanson Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (118, 'Yamia', 'Pre-emptive exuding superstructure', '00697 Oxford Point');
INSERT INTO box.locations (id, name, description, address) VALUES (119, 'Aimbu', 'Down-sized fault-tolerant frame', '13 1st Place');
INSERT INTO box.locations (id, name, description, address) VALUES (120, 'Leexo', 'Enhanced zero defect forecast', '3103 Golf View Way');
INSERT INTO box.locations (id, name, description, address) VALUES (121, 'Meeveo', 'Multi-layered web-enabled ability', '6152 Roxbury Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (122, 'Jayo', 'Enterprise-wide scalable framework', '89363 Emmet Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (123, 'Omba', 'Organized radical throughput', '17 Jenna Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (124, 'Babbleblab', 'Virtual demand-driven utilisation', '6657 Moose Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (125, 'Cogidoo', 'Profound attitude-oriented solution', '7529 American Ash Center');
INSERT INTO box.locations (id, name, description, address) VALUES (126, 'Topiczoom', 'Sharable high-level ability', '7642 Washington Road');
INSERT INTO box.locations (id, name, description, address) VALUES (127, 'Blogpad', 'Customer-focused dedicated adapter', '4688 Scott Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (128, 'Feedfire', 'Triple-buffered global migration', '90 Nova Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (129, 'Kaymbo', 'Universal optimizing complexity', '3 Raven Park');
INSERT INTO box.locations (id, name, description, address) VALUES (130, 'Brightdog', 'Enhanced systemic project', '50702 Eagle Crest Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (131, 'Voolia', 'Object-based background standardization', '5516 Surrey Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (132, 'Reallinks', 'Robust coherent parallelism', '10015 Straubel Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (133, 'Brightbean', 'Ameliorated solution-oriented project', '2 Pond Road');
INSERT INTO box.locations (id, name, description, address) VALUES (134, 'Wordtune', 'Organic upward-trending Graphic Interface', '35759 Schlimgen Place');
INSERT INTO box.locations (id, name, description, address) VALUES (135, 'Kazio', 'Cross-group foreground utilisation', '9 Reinke Court');
INSERT INTO box.locations (id, name, description, address) VALUES (136, 'Meemm', 'Progressive 6th generation website', '4 Monument Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (137, 'Feednation', 'Up-sized bi-directional instruction set', '4 Kinsman Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (138, 'Edgetag', 'User-centric solution-oriented pricing structure', '281 Superior Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (139, 'Kazu', 'Integrated responsive customer loyalty', '8830 Sloan Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (140, 'Trilith', 'Enterprise-wide transitional parallelism', '53 Lunder Park');
INSERT INTO box.locations (id, name, description, address) VALUES (141, 'Omba', 'Synergized upward-trending initiative', '15 Leroy Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (142, 'Yacero', 'Total homogeneous encryption', '70547 Bonner Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (143, 'Zooxo', 'Multi-lateral heuristic hierarchy', '347 Hollow Ridge Court');
INSERT INTO box.locations (id, name, description, address) VALUES (144, 'Gigabox', 'Distributed 5th generation collaboration', '89 Rieder Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (145, 'Minyx', 'Proactive fault-tolerant definition', '4 Ohio Place');
INSERT INTO box.locations (id, name, description, address) VALUES (146, 'Topiczoom', 'Fully-configurable scalable forecast', '47324 Hoepker Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (147, 'Riffpath', 'Fundamental hybrid definition', '01 Daystar Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (148, 'Jaxbean', 'Adaptive maximized groupware', '3587 Grayhawk Way');
INSERT INTO box.locations (id, name, description, address) VALUES (149, 'Skyba', 'Versatile attitude-oriented complexity', '8615 Gateway Road');
INSERT INTO box.locations (id, name, description, address) VALUES (150, 'Gevee', 'Business-focused holistic methodology', '65932 Florence Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (151, 'Leexo', 'Ameliorated context-sensitive local area network', '12 Hoffman Street');
INSERT INTO box.locations (id, name, description, address) VALUES (152, 'Yakijo', 'Realigned multi-state structure', '3 Monument Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (153, 'Quatz', 'Stand-alone non-volatile system engine', '2 Oak Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (154, 'Dynabox', 'Future-proofed empowering internet solution', '40 Pennsylvania Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (155, 'Realmix', 'Assimilated attitude-oriented service-desk', '78550 Fieldstone Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (156, 'Youbridge', 'Team-oriented intermediate moratorium', '5 Mccormick Place');
INSERT INTO box.locations (id, name, description, address) VALUES (157, 'Mynte', 'Streamlined attitude-oriented emulation', '4 Village Green Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (158, 'Teklist', 'Innovative needs-based info-mediaries', '6323 Farmco Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (159, 'Kayveo', 'Streamlined multimedia middleware', '21751 Shoshone Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (160, 'Thoughtsphere', 'Progressive multi-state Graphical User Interface', '07 Hagan Street');
INSERT INTO box.locations (id, name, description, address) VALUES (161, 'Kwideo', 'Future-proofed needs-based paradigm', '83 Bowman Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (162, 'Edgetag', 'Up-sized dynamic forecast', '892 Basil Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (163, 'Fivechat', 'Open-source foreground attitude', '67 Warbler Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (164, 'Feednation', 'Function-based asynchronous Graphic Interface', '2 Village Place');
INSERT INTO box.locations (id, name, description, address) VALUES (165, 'Oodoo', 'Programmable 3rd generation Graphic Interface', '08859 Messerschmidt Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (166, 'Twitterbeat', 'Multi-lateral zero administration toolset', '3 Forest Dale Center');
INSERT INTO box.locations (id, name, description, address) VALUES (167, 'Wordware', 'Optional cohesive firmware', '98 Dapin Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (168, 'Jetwire', 'Stand-alone encompassing throughput', '28 Milwaukee Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (169, 'Camimbo', 'Self-enabling exuding moratorium', '15 Portage Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (170, 'Bubblemix', 'Inverse content-based interface', '06043 Fair Oaks Center');
INSERT INTO box.locations (id, name, description, address) VALUES (171, 'Edgeclub', 'Customer-focused asynchronous architecture', '829 Gateway Way');
INSERT INTO box.locations (id, name, description, address) VALUES (172, 'Quire', 'Phased contextually-based solution', '0 Hazelcrest Point');
INSERT INTO box.locations (id, name, description, address) VALUES (173, 'Kayveo', 'Multi-lateral 3rd generation hardware', '2869 Bluejay Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (174, 'Camimbo', 'Cross-platform demand-driven attitude', '00262 Kedzie Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (175, 'Pixope', 'Monitored multimedia matrix', '5619 Westend Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (176, 'Yakijo', 'Compatible real-time open system', '6559 Forest Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (177, 'Feedspan', 'Cross-group human-resource internet solution', '128 Pearson Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (178, 'Dabjam', 'Object-based dedicated implementation', '7397 Alpine Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (179, 'Skyndu', 'User-friendly zero administration capacity', '3 Parkside Center');
INSERT INTO box.locations (id, name, description, address) VALUES (180, 'BlogXS', 'Ameliorated user-facing intranet', '565 Longview Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (181, 'Tekfly', 'Organic multi-tasking capability', '39 Spaight Road');
INSERT INTO box.locations (id, name, description, address) VALUES (182, 'Edgewire', 'Vision-oriented real-time contingency', '59601 Cottonwood Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (183, 'Voonder', 'Reduced mission-critical local area network', '57207 Autumn Leaf Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (184, 'Tagchat', 'Progressive asymmetric concept', '112 Lerdahl Court');
INSERT INTO box.locations (id, name, description, address) VALUES (185, 'Realfire', 'Programmable clear-thinking open architecture', '5 Lindbergh Road');
INSERT INTO box.locations (id, name, description, address) VALUES (186, 'Pixope', 'Cross-group directional project', '87864 Londonderry Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (187, 'Agimba', 'Self-enabling composite matrix', '991 Welch Court');
INSERT INTO box.locations (id, name, description, address) VALUES (188, 'Zoonoodle', 'Customer-focused clear-thinking matrices', '71 Sycamore Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (189, 'Wordtune', 'Multi-layered logistical throughput', '98890 Scoville Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (190, 'Oyope', 'Mandatory well-modulated artificial intelligence', '288 Russell Court');
INSERT INTO box.locations (id, name, description, address) VALUES (191, 'Youfeed', 'Customizable 5th generation synergy', '90053 Bonner Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (192, 'Twitterworks', 'Distributed global adapter', '85 Esch Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (193, 'Tagtune', 'Stand-alone executive flexibility', '41 3rd Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (194, 'Wikizz', 'Centralized background parallelism', '0 Independence Road');
INSERT INTO box.locations (id, name, description, address) VALUES (195, 'Riffwire', 'Compatible static projection', '3044 Cordelia Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (196, 'Katz', 'Streamlined stable strategy', '4855 Johnson Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (197, 'Yodo', 'Secured maximized process improvement', '2 Farwell Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (198, 'Kwideo', 'Compatible asynchronous knowledge user', '4 Arkansas Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (199, 'JumpXS', 'Self-enabling disintermediate capacity', '99 Bunker Hill Street');
INSERT INTO box.locations (id, name, description, address) VALUES (200, 'Youfeed', 'Proactive radical alliance', '701 Pennsylvania Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (201, 'Linkbridge', 'Horizontal local attitude', '96109 Towne Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (202, 'Rhybox', 'Fundamental human-resource support', '6393 Brown Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (203, 'Devbug', 'Intuitive dynamic adapter', '6415 Clyde Gallagher Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (204, 'Buzzster', 'Grass-roots 24/7 function', '08 Lindbergh Street');
INSERT INTO box.locations (id, name, description, address) VALUES (205, 'Wikibox', 'Configurable zero administration conglomeration', '71720 Grasskamp Point');
INSERT INTO box.locations (id, name, description, address) VALUES (206, 'Lajo', 'Seamless fault-tolerant knowledge base', '281 Westport Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (207, 'Jazzy', 'Profit-focused client-server adapter', '46 Sundown Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (208, 'Chatterbridge', 'Synergistic eco-centric workforce', '58 Iowa Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (209, 'Chatterbridge', 'Quality-focused zero tolerance customer loyalty', '2706 Green Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (210, 'Divanoodle', 'Grass-roots fresh-thinking throughput', '16 Eastwood Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (211, 'Trilia', 'Customer-focused demand-driven groupware', '4333 Garrison Street');
INSERT INTO box.locations (id, name, description, address) VALUES (212, 'Voolia', 'Reduced tangible parallelism', '18981 Johnson Point');
INSERT INTO box.locations (id, name, description, address) VALUES (213, 'Photojam', 'Stand-alone radical archive', '32 Grayhawk Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (214, 'Yadel', 'Optional maximized knowledge base', '7661 Butternut Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (215, 'Divape', 'Reactive fresh-thinking archive', '3339 Hoffman Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (216, 'Izio', 'Optional disintermediate firmware', '97588 Hanover Point');
INSERT INTO box.locations (id, name, description, address) VALUES (217, 'Meevee', 'Configurable leading edge ability', '15 Wayridge Place');
INSERT INTO box.locations (id, name, description, address) VALUES (218, 'Yacero', 'Devolved 3rd generation utilisation', '82371 Thompson Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (219, 'Wikibox', 'Switchable object-oriented alliance', '44 Division Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (220, 'Rhycero', 'Pre-emptive bottom-line open architecture', '75383 Bunker Hill Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (221, 'Yacero', 'Triple-buffered homogeneous Graphic Interface', '93 Dryden Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (222, 'Yacero', 'Innovative zero tolerance collaboration', '3 Erie Court');
INSERT INTO box.locations (id, name, description, address) VALUES (223, 'JumpXS', 'Cross-group intermediate function', '64867 Carpenter Street');
INSERT INTO box.locations (id, name, description, address) VALUES (224, 'Gabtype', 'Future-proofed stable concept', '37 Crowley Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (225, 'Brainsphere', 'Switchable dynamic moratorium', '34 Farragut Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (226, 'Divape', 'Synergistic multimedia attitude', '6 Susan Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (227, 'BlogXS', 'Upgradable bottom-line customer loyalty', '62 Welch Center');
INSERT INTO box.locations (id, name, description, address) VALUES (228, 'Dabjam', 'Synergized modular application', '218 Chive Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (229, 'Aimbo', 'Progressive needs-based structure', '2 Russell Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (230, 'Rhynoodle', 'Customizable human-resource policy', '44 Oriole Park');
INSERT INTO box.locations (id, name, description, address) VALUES (231, 'Einti', 'Inverse exuding middleware', '664 Doe Crossing Street');
INSERT INTO box.locations (id, name, description, address) VALUES (232, 'Browsedrive', 'Open-source neutral model', '532 Portage Park');
INSERT INTO box.locations (id, name, description, address) VALUES (233, 'Wordpedia', 'Front-line intermediate access', '1142 Harper Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (234, 'Linkbuzz', 'Persevering coherent knowledge user', '2 Knutson Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (235, 'Yakitri', 'Virtual leading edge definition', '7797 Daystar Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (236, 'Rhybox', 'Implemented responsive artificial intelligence', '2 Leroy Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (237, 'Demivee', 'Right-sized context-sensitive ability', '58211 Farmco Road');
INSERT INTO box.locations (id, name, description, address) VALUES (238, 'Jazzy', 'Enterprise-wide tertiary hierarchy', '934 Wayridge Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (239, 'Jabberbean', 'Stand-alone intangible policy', '987 Superior Park');
INSERT INTO box.locations (id, name, description, address) VALUES (240, 'Yakidoo', 'Future-proofed analyzing contingency', '50612 Mayer Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (241, 'Tagchat', 'Enhanced stable firmware', '1 Macpherson Court');
INSERT INTO box.locations (id, name, description, address) VALUES (242, 'Quimba', 'Fully-configurable high-level middleware', '60018 Anzinger Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (243, 'Edgewire', 'Organic secondary secured line', '83473 Village Point');
INSERT INTO box.locations (id, name, description, address) VALUES (244, 'Browsezoom', 'Proactive static initiative', '66438 Myrtle Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (245, 'Realmix', 'Centralized systematic time-frame', '4 Nancy Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (246, 'Aivee', 'Face to face mission-critical extranet', '29 Moulton Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (247, 'Eamia', 'Customer-focused secondary methodology', '5 Esch Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (248, 'Omba', 'Stand-alone next generation customer loyalty', '0056 Sunfield Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (249, 'Yadel', 'Intuitive cohesive utilisation', '75 Blaine Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (250, 'Linklinks', 'Optimized neutral archive', '8223 Melvin Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (251, 'Leenti', 'Upgradable user-facing complexity', '18 Goodland Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (252, 'Tagpad', 'Upgradable 24/7 project', '8 Charing Cross Place');
INSERT INTO box.locations (id, name, description, address) VALUES (253, 'Blognation', 'Cloned zero administration support', '90002 Burning Wood Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (254, 'Livefish', 'Inverse multi-tasking software', '33 Rusk Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (255, 'Bluejam', 'Operative fault-tolerant infrastructure', '39 Kinsman Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (256, 'Skiptube', 'Triple-buffered reciprocal encoding', '034 Arrowood Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (257, 'Brainbox', 'Ameliorated tertiary throughput', '70 Swallow Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (258, 'BlogXS', 'Switchable homogeneous application', '0 Warbler Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (259, 'Wikizz', 'Synergized coherent firmware', '548 Hudson Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (260, 'Blogtag', 'Grass-roots static open system', '9 Jana Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (261, 'Trilith', 'Fully-configurable neutral implementation', '189 Old Gate Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (262, 'Brainverse', 'Vision-oriented real-time archive', '12 Maywood Place');
INSERT INTO box.locations (id, name, description, address) VALUES (263, 'Fivespan', 'Re-contextualized responsive structure', '74 Mitchell Court');
INSERT INTO box.locations (id, name, description, address) VALUES (264, 'Demizz', 'Reactive tangible utilisation', '68218 Pierstorff Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (265, 'Rhycero', 'Team-oriented object-oriented encryption', '510 Linden Road');
INSERT INTO box.locations (id, name, description, address) VALUES (266, 'Brainsphere', 'Open-architected bifurcated policy', '2 Haas Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (267, 'Ntags', 'Re-engineered zero tolerance software', '7241 Oneill Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (268, 'Kare', 'Automated client-driven extranet', '0207 Kennedy Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (269, 'Zoonoodle', 'Down-sized eco-centric migration', '224 Kensington Place');
INSERT INTO box.locations (id, name, description, address) VALUES (270, 'Quire', 'Devolved bi-directional task-force', '4844 Dottie Street');
INSERT INTO box.locations (id, name, description, address) VALUES (271, 'Flipopia', 'Inverse bandwidth-monitored circuit', '3 Jenifer Street');
INSERT INTO box.locations (id, name, description, address) VALUES (272, 'Dabvine', 'Robust optimizing instruction set', '68 Warbler Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (273, 'Oloo', 'Business-focused user-facing migration', '5 Old Shore Street');
INSERT INTO box.locations (id, name, description, address) VALUES (274, 'Realcube', 'Reactive zero tolerance toolset', '06 Westerfield Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (275, 'Dynava', 'Persevering fault-tolerant standardization', '593 Petterle Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (276, 'Yodel', 'Open-source maximized database', '6826 Troy Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (277, 'Oyondu', 'Multi-lateral zero administration structure', '8845 Schiller Point');
INSERT INTO box.locations (id, name, description, address) VALUES (278, 'Browsedrive', 'Face to face zero defect local area network', '0979 Almo Point');
INSERT INTO box.locations (id, name, description, address) VALUES (279, 'Eabox', 'Triple-buffered attitude-oriented alliance', '5 Warner Center');
INSERT INTO box.locations (id, name, description, address) VALUES (280, 'Browsetype', 'Realigned modular concept', '6394 American Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (281, 'Fadeo', 'Ergonomic actuating functionalities', '207 Del Mar Place');
INSERT INTO box.locations (id, name, description, address) VALUES (282, 'Skaboo', 'Cross-group full-range emulation', '0 Prentice Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (283, 'Edgeblab', 'Business-focused interactive moderator', '66528 Petterle Way');
INSERT INTO box.locations (id, name, description, address) VALUES (284, 'Katz', 'Optional directional policy', '97216 Morningstar Point');
INSERT INTO box.locations (id, name, description, address) VALUES (285, 'Dynabox', 'Vision-oriented uniform access', '4 Forster Road');
INSERT INTO box.locations (id, name, description, address) VALUES (286, 'Meemm', 'Distributed needs-based system engine', '704 Mcguire Center');
INSERT INTO box.locations (id, name, description, address) VALUES (287, 'Skipfire', 'Programmable analyzing knowledge user', '65 Morningstar Park');
INSERT INTO box.locations (id, name, description, address) VALUES (288, 'Tagcat', 'Expanded empowering time-frame', '4 Prairie Rose Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (289, 'Quinu', 'Front-line object-oriented secured line', '17 Clyde Gallagher Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (290, 'Devbug', 'Programmable cohesive middleware', '42 Morrow Way');
INSERT INTO box.locations (id, name, description, address) VALUES (291, 'Oozz', 'Optional homogeneous synergy', '426 Fisk Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (292, 'Topicware', 'De-engineered homogeneous firmware', '9 Maple Place');
INSERT INTO box.locations (id, name, description, address) VALUES (293, 'Devcast', 'Future-proofed background implementation', '55506 Victoria Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (294, 'Tagtune', 'Sharable high-level parallelism', '46 Fulton Point');
INSERT INTO box.locations (id, name, description, address) VALUES (295, 'Shuffledrive', 'Progressive demand-driven parallelism', '9261 Killdeer Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (296, 'Plajo', 'Multi-lateral exuding encryption', '2465 Schmedeman Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (297, 'Roodel', 'Universal maximized artificial intelligence', '9 Spenser Way');
INSERT INTO box.locations (id, name, description, address) VALUES (298, 'Ailane', 'Enhanced explicit data-warehouse', '1054 Sauthoff Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (299, 'Skalith', 'Ameliorated local toolset', '50 Charing Cross Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (300, 'Topdrive', 'Multi-tiered uniform neural-net', '46292 Village Green Way');
INSERT INTO box.locations (id, name, description, address) VALUES (301, 'Jabberstorm', 'Diverse leading edge model', '8 Summerview Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (302, 'Jetwire', 'Versatile web-enabled approach', '66 Moulton Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (303, 'Oyonder', 'Enterprise-wide multi-tasking implementation', '86991 Leroy Center');
INSERT INTO box.locations (id, name, description, address) VALUES (304, 'Oyondu', 'Business-focused heuristic synergy', '2461 Sundown Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (305, 'Livetube', 'Versatile user-facing throughput', '570 Sunbrook Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (306, 'Avamm', 'Integrated 6th generation interface', '91 Messerschmidt Way');
INSERT INTO box.locations (id, name, description, address) VALUES (307, 'Tagopia', 'Focused analyzing monitoring', '6588 Crest Line Road');
INSERT INTO box.locations (id, name, description, address) VALUES (308, 'Voolith', 'Compatible solution-oriented toolset', '4 Elgar Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (309, 'Trilia', 'User-centric secondary architecture', '2 David Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (310, 'Jayo', 'Reduced fault-tolerant budgetary management', '48150 Dawn Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (311, 'Kamba', 'Reverse-engineered dedicated system engine', '90083 Declaration Street');
INSERT INTO box.locations (id, name, description, address) VALUES (312, 'Browsetype', 'Versatile stable knowledge base', '387 Dexter Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (313, 'Livefish', 'Progressive optimal archive', '635 5th Road');
INSERT INTO box.locations (id, name, description, address) VALUES (314, 'Quinu', 'Vision-oriented mission-critical portal', '58 Shasta Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (315, 'Voonyx', 'Reduced methodical methodology', '53091 Nova Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (316, 'Topicshots', 'Adaptive holistic migration', '7 Forster Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (317, 'Demizz', 'Intuitive mission-critical forecast', '5 Daystar Place');
INSERT INTO box.locations (id, name, description, address) VALUES (318, 'Bluezoom', 'Operative bandwidth-monitored attitude', '97177 Rieder Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (319, 'Linklinks', 'Upgradable 3rd generation functionalities', '9953 Kim Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (320, 'Kare', 'Re-engineered non-volatile capacity', '045 Macpherson Center');
INSERT INTO box.locations (id, name, description, address) VALUES (321, 'Shuffledrive', 'Virtual exuding superstructure', '90970 Drewry Place');
INSERT INTO box.locations (id, name, description, address) VALUES (322, 'Twitterbeat', 'Horizontal exuding budgetary management', '01 Briar Crest Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (323, 'Quaxo', 'Upgradable demand-driven database', '416 Kenwood Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (324, 'Snaptags', 'Future-proofed intermediate projection', '206 Barnett Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (325, 'Oyoyo', 'Horizontal real-time infrastructure', '3 Vidon Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (326, 'Roodel', 'Proactive object-oriented website', '6276 Kingsford Road');
INSERT INTO box.locations (id, name, description, address) VALUES (327, 'Avavee', 'Fully-configurable even-keeled knowledge base', '98 Mcbride Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (328, 'Midel', 'Multi-lateral optimal conglomeration', '19042 Superior Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (329, 'Gigazoom', 'Object-based didactic neural-net', '52935 Mallard Place');
INSERT INTO box.locations (id, name, description, address) VALUES (330, 'Jabbersphere', 'Configurable global product', '6 Sundown Road');
INSERT INTO box.locations (id, name, description, address) VALUES (331, 'Buzzbean', 'Cloned global archive', '62 Magdeline Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (332, 'Trudoo', 'Organic grid-enabled software', '7 Buhler Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (333, 'Thoughtbeat', 'Virtual client-driven complexity', '087 Grayhawk Street');
INSERT INTO box.locations (id, name, description, address) VALUES (334, 'Avavee', 'Multi-layered methodical strategy', '85 Montana Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (335, 'Thoughtstorm', 'Extended optimizing challenge', '7 Dennis Park');
INSERT INTO box.locations (id, name, description, address) VALUES (336, 'Twimbo', 'Configurable maximized structure', '2 Forster Street');
INSERT INTO box.locations (id, name, description, address) VALUES (337, 'Avaveo', 'Total systematic instruction set', '34055 Sugar Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (338, 'Gabtune', 'Grass-roots actuating monitoring', '4 Truax Court');
INSERT INTO box.locations (id, name, description, address) VALUES (339, 'Dynava', 'Multi-tiered demand-driven portal', '15 Carioca Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (340, 'Skaboo', 'Reduced composite concept', '66 Red Cloud Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (341, 'Skyble', 'Optimized 4th generation help-desk', '146 Spohn Point');
INSERT INTO box.locations (id, name, description, address) VALUES (342, 'Meevee', 'Versatile systemic service-desk', '62 Lawn Center');
INSERT INTO box.locations (id, name, description, address) VALUES (343, 'Skinix', 'Automated well-modulated synergy', '2 Lake View Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (344, 'Buzzbean', 'Integrated content-based implementation', '44 Heffernan Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (345, 'Trilia', 'Compatible discrete productivity', '1 Delladonna Point');
INSERT INTO box.locations (id, name, description, address) VALUES (346, 'Kwinu', 'Multi-layered client-server array', '22070 Lyons Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (347, 'Youspan', 'Operative next generation application', '85 Norway Maple Court');
INSERT INTO box.locations (id, name, description, address) VALUES (348, 'Devcast', 'Front-line multi-tasking hub', '8926 Menomonie Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (349, 'Yacero', 'Customizable bandwidth-monitored open system', '4 Bay Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (350, 'Voolia', 'Progressive asymmetric extranet', '5980 Montana Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (351, 'Bubblemix', 'Quality-focused tangible application', '73156 Hanson Point');
INSERT INTO box.locations (id, name, description, address) VALUES (352, 'Wikizz', 'Switchable holistic website', '2 Barby Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (353, 'Vidoo', 'Multi-layered bottom-line architecture', '8800 Arizona Park');
INSERT INTO box.locations (id, name, description, address) VALUES (354, 'Fatz', 'Exclusive systematic data-warehouse', '435 Jenna Street');
INSERT INTO box.locations (id, name, description, address) VALUES (355, 'Bubblebox', 'De-engineered explicit service-desk', '9 Arapahoe Center');
INSERT INTO box.locations (id, name, description, address) VALUES (356, 'Edgetag', 'Proactive background approach', '8149 Meadow Ridge Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (357, 'Jabbercube', 'Total reciprocal circuit', '201 Vermont Road');
INSERT INTO box.locations (id, name, description, address) VALUES (358, 'Jazzy', 'Integrated demand-driven model', '1876 Colorado Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (359, 'Babbleset', 'Customizable high-level secured line', '5949 Bay Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (360, 'Jetwire', 'Multi-channelled local conglomeration', '41 Merchant Point');
INSERT INTO box.locations (id, name, description, address) VALUES (361, 'Feedmix', 'Reactive asynchronous task-force', '58590 Monument Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (362, 'Avamm', 'Profit-focused hybrid adapter', '4 Springview Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (363, 'Topiclounge', 'Enterprise-wide radical productivity', '411 Shoshone Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (364, 'Trilia', 'User-centric coherent extranet', '99 Eliot Park');
INSERT INTO box.locations (id, name, description, address) VALUES (365, 'Browsecat', 'Integrated bandwidth-monitored moderator', '568 Saint Paul Park');
INSERT INTO box.locations (id, name, description, address) VALUES (366, 'Bubblemix', 'Implemented static project', '1 Fieldstone Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (367, 'Meedoo', 'Function-based intermediate superstructure', '221 Hintze Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (368, 'Dablist', 'Enterprise-wide systemic interface', '5416 Del Sol Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (369, 'Livetube', 'Monitored fresh-thinking neural-net', '1 Sachtjen Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (370, 'Devpulse', 'Organized mobile analyzer', '0 Mallard Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (371, 'Quinu', 'Stand-alone leading edge success', '9874 Harper Road');
INSERT INTO box.locations (id, name, description, address) VALUES (372, 'LiveZ', 'Multi-channelled optimal initiative', '1 Vermont Way');
INSERT INTO box.locations (id, name, description, address) VALUES (373, 'Photospace', 'Extended upward-trending neural-net', '95 Rutledge Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (374, 'Reallinks', 'Persistent bi-directional matrices', '114 Tony Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (375, 'Flashspan', 'Profit-focused needs-based installation', '01 Homewood Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (376, 'Babbleopia', 'Synchronised context-sensitive alliance', '5484 Sommers Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (377, 'Zoomlounge', 'Multi-lateral zero tolerance solution', '550 Hintze Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (378, 'Katz', 'Robust eco-centric matrix', '7329 Cherokee Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (379, 'Avamm', 'Configurable explicit contingency', '56 Sunbrook Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (380, 'Centimia', 'Total attitude-oriented hierarchy', '38608 Ilene Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (381, 'Topdrive', 'Realigned attitude-oriented implementation', '89953 Sunbrook Point');
INSERT INTO box.locations (id, name, description, address) VALUES (382, 'Zazio', 'Secured transitional methodology', '32832 Iowa Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (383, 'Quimm', 'Exclusive logistical database', '121 Melvin Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (384, 'InnoZ', 'Balanced intangible ability', '02350 Lyons Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (385, 'Dynava', 'Visionary user-facing neural-net', '5 Grover Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (386, 'Trilia', 'Open-source exuding hardware', '21352 Namekagon Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (387, 'Jaxnation', 'Upgradable hybrid time-frame', '2 Londonderry Point');
INSERT INTO box.locations (id, name, description, address) VALUES (388, 'Skyndu', 'Up-sized homogeneous service-desk', '591 Marquette Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (389, 'Mita', 'Multi-tiered context-sensitive process improvement', '7129 Fordem Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (390, 'Topiclounge', 'Function-based hybrid model', '83465 Rockefeller Park');
INSERT INTO box.locations (id, name, description, address) VALUES (391, 'Kimia', 'Synchronised optimizing challenge', '315 Spohn Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (392, 'Shuffletag', 'Synergistic content-based flexibility', '67634 Little Fleur Street');
INSERT INTO box.locations (id, name, description, address) VALUES (393, 'Yotz', 'Face to face client-server moderator', '6001 Morningstar Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (394, 'Demizz', 'Upgradable homogeneous paradigm', '754 Tony Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (395, 'Tambee', 'Extended asynchronous system engine', '27 Dapin Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (396, 'Tazzy', 'Optimized dedicated product', '49 Barnett Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (397, 'Avaveo', 'Profound bi-directional budgetary management', '498 Summerview Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (398, 'Feedfish', 'Centralized zero defect info-mediaries', '460 Green Court');
INSERT INTO box.locations (id, name, description, address) VALUES (399, 'Buzzbean', 'Centralized heuristic open system', '2642 Hallows Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (400, 'Thoughtmix', 'Future-proofed next generation hub', '333 Thierer Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (401, 'Teklist', 'Enterprise-wide optimizing interface', '70 Monterey Way');
INSERT INTO box.locations (id, name, description, address) VALUES (402, 'Zoomlounge', 'Business-focused 24 hour service-desk', '8019 Dryden Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (403, 'Trudoo', 'Customer-focused coherent implementation', '27117 Logan Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (404, 'Yakijo', 'Advanced optimal collaboration', '7 Knutson Court');
INSERT INTO box.locations (id, name, description, address) VALUES (405, 'Gabtune', 'Innovative upward-trending orchestration', '2999 Novick Way');
INSERT INTO box.locations (id, name, description, address) VALUES (406, 'Oyoyo', 'Robust systematic monitoring', '1212 Northview Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (407, 'Mybuzz', 'Networked didactic analyzer', '5 Kim Park');
INSERT INTO box.locations (id, name, description, address) VALUES (408, 'Talane', 'Enhanced executive budgetary management', '93651 Tomscot Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (409, 'Shuffledrive', 'Diverse leading edge policy', '1141 Old Gate Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (410, 'Oozz', 'Total mobile definition', '9633 Granby Court');
INSERT INTO box.locations (id, name, description, address) VALUES (411, 'Mynte', 'De-engineered 5th generation capability', '6 Stephen Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (412, 'Quimba', 'Open-source interactive alliance', '58190 Maple Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (413, 'Kazu', 'Streamlined 24/7 infrastructure', '10968 Russell Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (414, 'Browsebug', 'Fundamental maximized orchestration', '14749 Bellgrove Road');
INSERT INTO box.locations (id, name, description, address) VALUES (415, 'Meedoo', 'Networked solution-oriented instruction set', '49 Oneill Road');
INSERT INTO box.locations (id, name, description, address) VALUES (416, 'Chatterbridge', 'Synergistic client-driven adapter', '50 Darwin Center');
INSERT INTO box.locations (id, name, description, address) VALUES (417, 'Kanoodle', 'Virtual context-sensitive support', '53 Canary Court');
INSERT INTO box.locations (id, name, description, address) VALUES (418, 'Eazzy', 'Managed regional structure', '185 Portage Street');
INSERT INTO box.locations (id, name, description, address) VALUES (419, 'Meemm', 'Polarised regional database', '9478 Elka Park');
INSERT INTO box.locations (id, name, description, address) VALUES (420, 'Eare', 'Expanded upward-trending portal', '052 Scofield Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (421, 'Feednation', 'Organic fresh-thinking frame', '4 Tennyson Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (422, 'Tekfly', 'Ameliorated asynchronous implementation', '59226 Autumn Leaf Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (423, 'Ailane', 'Up-sized contextually-based workforce', '394 Donald Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (424, 'Kazu', 'Reduced intermediate array', '88 Sunfield Way');
INSERT INTO box.locations (id, name, description, address) VALUES (425, 'Photobug', 'Reduced uniform time-frame', '578 Comanche Street');
INSERT INTO box.locations (id, name, description, address) VALUES (426, 'Brainverse', 'Multi-channelled didactic architecture', '4 Roxbury Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (427, 'Twitterbridge', 'Pre-emptive context-sensitive service-desk', '54673 Wayridge Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (428, 'Livepath', 'Function-based global methodology', '46271 Ridgeway Way');
INSERT INTO box.locations (id, name, description, address) VALUES (429, 'Browsedrive', 'Enhanced next generation capability', '42 Kinsman Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (430, 'Eamia', 'Multi-tiered 24 hour synergy', '1 Barby Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (431, 'Tagchat', 'Customizable didactic emulation', '1878 Kedzie Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (432, 'Realcube', 'Business-focused hybrid parallelism', '92 Carioca Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (433, 'Topiczoom', 'Devolved heuristic workforce', '383 Warrior Way');
INSERT INTO box.locations (id, name, description, address) VALUES (434, 'Minyx', 'Function-based human-resource attitude', '1 Stuart Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (435, 'Muxo', 'Face to face neutral synergy', '70053 Annamark Place');
INSERT INTO box.locations (id, name, description, address) VALUES (436, 'Photobean', 'Focused directional support', '65 Eliot Street');
INSERT INTO box.locations (id, name, description, address) VALUES (437, 'Npath', 'Persistent dynamic system engine', '08 Southridge Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (438, 'Voomm', 'Cross-platform responsive superstructure', '845 Ridgeview Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (439, 'Zoovu', 'Polarised even-keeled help-desk', '24641 Bashford Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (440, 'Yakidoo', 'Monitored zero defect function', '21277 Marquette Park');
INSERT INTO box.locations (id, name, description, address) VALUES (441, 'Thoughtstorm', 'Universal maximized alliance', '70 Knutson Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (442, 'Aibox', 'Fundamental composite moratorium', '7658 Ruskin Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (443, 'Yakidoo', 'Upgradable contextually-based functionalities', '231 Saint Paul Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (444, 'Gigabox', 'Re-contextualized executive customer loyalty', '8205 Hayes Park');
INSERT INTO box.locations (id, name, description, address) VALUES (445, 'Demizz', 'Open-architected optimal neural-net', '03227 Glendale Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (446, 'Linkbuzz', 'Re-engineered asymmetric implementation', '52 Anzinger Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (447, 'Yambee', 'Innovative encompassing groupware', '19086 Carberry Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (448, 'Wikizz', 'Horizontal dedicated intranet', '1 Dryden Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (449, 'Livepath', 'Stand-alone zero defect utilisation', '75 Hagan Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (450, 'Gigabox', 'Focused demand-driven structure', '3649 Hoard Center');
INSERT INTO box.locations (id, name, description, address) VALUES (451, 'Podcat', 'Future-proofed scalable extranet', '1 Burrows Hill');
INSERT INTO box.locations (id, name, description, address) VALUES (452, 'Eadel', 'Object-based global methodology', '67 Summer Ridge Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (453, 'Flipstorm', 'Public-key zero defect portal', '2051 Northland Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (454, 'Wikibox', 'Centralized didactic benchmark', '2 Meadow Ridge Street');
INSERT INTO box.locations (id, name, description, address) VALUES (455, 'Geba', 'Phased attitude-oriented capability', '565 Bellgrove Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (456, 'Buzzbean', 'Reactive secondary methodology', '54 Loeprich Center');
INSERT INTO box.locations (id, name, description, address) VALUES (457, 'Oyope', 'Realigned maximized frame', '698 Hagan Park');
INSERT INTO box.locations (id, name, description, address) VALUES (458, 'Dabtype', 'Devolved system-worthy superstructure', '7 Ilene Alley');
INSERT INTO box.locations (id, name, description, address) VALUES (459, 'Twitterlist', 'Open-architected secondary workforce', '16482 Monterey Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (460, 'Camido', 'Diverse non-volatile intranet', '460 Drewry Center');
INSERT INTO box.locations (id, name, description, address) VALUES (461, 'Gabvine', 'Multi-lateral logistical artificial intelligence', '225 Sutherland Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (462, 'Yozio', 'Face to face foreground infrastructure', '15 Pearson Parkway');
INSERT INTO box.locations (id, name, description, address) VALUES (463, 'Twimbo', 'Centralized asynchronous intranet', '84517 Schmedeman Street');
INSERT INTO box.locations (id, name, description, address) VALUES (464, 'Wordpedia', 'Managed motivating installation', '02 Division Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (465, 'Viva', 'Exclusive incremental parallelism', '8005 Erie Court');
INSERT INTO box.locations (id, name, description, address) VALUES (466, 'Kazu', 'Right-sized reciprocal contingency', '7 Luster Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (467, 'Rhyloo', 'Optional solution-oriented local area network', '3614 Charing Cross Lane');
INSERT INTO box.locations (id, name, description, address) VALUES (468, 'Realbuzz', 'Monitored 3rd generation success', '688 Northridge Pass');
INSERT INTO box.locations (id, name, description, address) VALUES (469, 'Zoovu', 'Synergistic attitude-oriented implementation', '64800 Cardinal Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (470, 'InnoZ', 'Visionary mobile superstructure', '3 Fisk Place');
INSERT INTO box.locations (id, name, description, address) VALUES (471, 'Flashpoint', 'Horizontal static utilisation', '635 Tennyson Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (472, 'Jazzy', 'Balanced tangible solution', '6 American Park');
INSERT INTO box.locations (id, name, description, address) VALUES (473, 'Jabberbean', 'Total asymmetric software', '929 Northland Road');
INSERT INTO box.locations (id, name, description, address) VALUES (474, 'Snaptags', 'Monitored uniform firmware', '3 Sutherland Trail');
INSERT INTO box.locations (id, name, description, address) VALUES (475, 'Rhyzio', 'Extended stable project', '0740 Raven Place');
INSERT INTO box.locations (id, name, description, address) VALUES (476, 'Cogilith', 'Synergistic high-level task-force', '083 Mallory Road');
INSERT INTO box.locations (id, name, description, address) VALUES (477, 'Eamia', 'Cross-platform non-volatile internet solution', '540 Mayer Street');
INSERT INTO box.locations (id, name, description, address) VALUES (478, 'Latz', 'Monitored even-keeled intranet', '90 Summer Ridge Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (479, 'Skimia', 'Re-contextualized dedicated instruction set', '42761 Quincy Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (480, 'Kanoodle', 'Exclusive upward-trending matrices', '20924 Forest Road');
INSERT INTO box.locations (id, name, description, address) VALUES (481, 'Yambee', 'Automated intermediate process improvement', '2920 Mcguire Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (482, 'Thoughtbridge', 'Synchronised interactive monitoring', '2 Everett Terrace');
INSERT INTO box.locations (id, name, description, address) VALUES (483, 'Thoughtsphere', 'Persevering uniform migration', '44169 Kim Crossing');
INSERT INTO box.locations (id, name, description, address) VALUES (484, 'Yotz', 'Ergonomic 24 hour data-warehouse', '423 Village Green Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (485, 'Flashpoint', 'Versatile bandwidth-monitored core', '761 Burrows Way');
INSERT INTO box.locations (id, name, description, address) VALUES (486, 'Aibox', 'Synchronised asymmetric product', '67805 Bellgrove Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (487, 'Yoveo', 'Re-engineered impactful leverage', '350 Express Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (488, 'Demimbu', 'Multi-lateral background matrix', '91857 Bluejay Junction');
INSERT INTO box.locations (id, name, description, address) VALUES (489, 'Tekfly', 'User-centric maximized product', '8854 Miller Court');
INSERT INTO box.locations (id, name, description, address) VALUES (490, 'Gabspot', 'Managed 3rd generation portal', '194 Golf Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (491, 'Brainbox', 'User-friendly empowering challenge', '42 Butternut Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (492, 'Kaymbo', 'Advanced clear-thinking encryption', '0 Chinook Street');
INSERT INTO box.locations (id, name, description, address) VALUES (493, 'Topicshots', 'Multi-channelled homogeneous task-force', '47265 Graceland Circle');
INSERT INTO box.locations (id, name, description, address) VALUES (494, 'Tekfly', 'User-friendly well-modulated projection', '2481 Swallow Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (495, 'Babblestorm', 'Universal impactful success', '1067 Fulton Park');
INSERT INTO box.locations (id, name, description, address) VALUES (496, 'Realcube', 'Adaptive context-sensitive complexity', '3 Northwestern Drive');
INSERT INTO box.locations (id, name, description, address) VALUES (497, 'Centidel', 'Universal systematic internet solution', '34 Pond Park');
INSERT INTO box.locations (id, name, description, address) VALUES (498, 'Browsecat', 'Up-sized multi-state knowledge user', '0 Buhler Avenue');
INSERT INTO box.locations (id, name, description, address) VALUES (499, 'Yoveo', 'Cloned local implementation', '1287 Barby Plaza');
INSERT INTO box.locations (id, name, description, address) VALUES (500, 'Yakidoo', 'Profit-focused uniform matrix', '47 Melody Junction');

-- Set Next ID Value to MAX ID
SELECT setval('box.locations_id_seq', (SELECT MAX(id) FROM box.locations));