INSERT INTO box.boxer_teams (id, name, description) VALUES (1, 'RGC', 'User-centric eco-centric moratorium');
INSERT INTO box.boxer_teams (id, name, description) VALUES (2, 'EDI', 'Robust fresh-thinking matrix');
INSERT INTO box.boxer_teams (id, name, description) VALUES (3, 'CBL^E', 'Decentralized 3rd generation paradigm');
INSERT INTO box.boxer_teams (id, name, description) VALUES (4, 'NCB', 'Business-focused human-resource conglomeration');
INSERT INTO box.boxer_teams (id, name, description) VALUES (5, 'GABC', 'Realigned didactic circuit');
INSERT INTO box.boxer_teams (id, name, description) VALUES (6, 'CSGP', 'Inverse mission-critical hardware');
INSERT INTO box.boxer_teams (id, name, description) VALUES (7, 'SSRI', 'Multi-lateral clear-thinking hub');
INSERT INTO box.boxer_teams (id, name, description) VALUES (8, 'AIZ', 'Devolved 5th generation Graphic Interface');
INSERT INTO box.boxer_teams (id, name, description) VALUES (9, 'ACM', 'Decentralized hybrid model');
INSERT INTO box.boxer_teams (id, name, description) VALUES (10, 'APEN', 'Cross-group reciprocal matrices');
INSERT INTO box.boxer_teams (id, name, description) VALUES (11, 'DPG', 'Re-engineered needs-based software');
INSERT INTO box.boxer_teams (id, name, description) VALUES (12, 'PUB', 'Multi-layered empowering capability');
INSERT INTO box.boxer_teams (id, name, description) VALUES (13, 'DAX', 'Ameliorated interactive encryption');
INSERT INTO box.boxer_teams (id, name, description) VALUES (14, 'AZRX', 'Right-sized non-volatile contingency');
INSERT INTO box.boxer_teams (id, name, description) VALUES (15, 'RNDB', 'Extended eco-centric approach');
INSERT INTO box.boxer_teams (id, name, description) VALUES (16, 'IVC', 'Vision-oriented exuding product');
INSERT INTO box.boxer_teams (id, name, description) VALUES (17, 'CNXR', 'Grass-roots empowering interface');
INSERT INTO box.boxer_teams (id, name, description) VALUES (18, 'RPM', 'Ameliorated bi-directional moderator');
INSERT INTO box.boxer_teams (id, name, description) VALUES (19, 'CRWS', 'Networked 5th generation complexity');
INSERT INTO box.boxer_teams (id, name, description) VALUES (20, 'RRTS', 'Open-architected empowering architecture');
INSERT INTO box.boxer_teams (id, name, description) VALUES (21, 'CSV', 'Future-proofed asymmetric standardization');
INSERT INTO box.boxer_teams (id, name, description) VALUES (22, 'ADX', 'Versatile interactive frame');
INSERT INTO box.boxer_teams (id, name, description) VALUES (23, 'HLX', 'Sharable 5th generation capacity');
INSERT INTO box.boxer_teams (id, name, description) VALUES (24, 'SCHN', 'Quality-focused zero tolerance solution');
INSERT INTO box.boxer_teams (id, name, description) VALUES (25, 'EXA', 'Synchronised eco-centric alliance');
INSERT INTO box.boxer_teams (id, name, description) VALUES (26, 'LBTYB', 'Expanded impactful concept');
INSERT INTO box.boxer_teams (id, name, description) VALUES (27, 'HVT.A', 'Object-based uniform moratorium');
INSERT INTO box.boxer_teams (id, name, description) VALUES (28, 'FDP', 'Organic homogeneous time-frame');
INSERT INTO box.boxer_teams (id, name, description) VALUES (29, 'LGND', 'Diverse logistical website');
INSERT INTO box.boxer_teams (id, name, description) VALUES (30, 'PAGP', 'Decentralized cohesive open system');
INSERT INTO box.boxer_teams (id, name, description) VALUES (31, 'TRMR', 'Phased static toolset');
INSERT INTO box.boxer_teams (id, name, description) VALUES (32, 'NMK^C', 'Profound executive policy');
INSERT INTO box.boxer_teams (id, name, description) VALUES (33, 'PLCE', 'Enterprise-wide solution-oriented service-desk');
INSERT INTO box.boxer_teams (id, name, description) VALUES (34, 'PID', 'Profit-focused disintermediate middleware');
INSERT INTO box.boxer_teams (id, name, description) VALUES (35, 'HESM', 'Synergized context-sensitive software');
INSERT INTO box.boxer_teams (id, name, description) VALUES (36, 'SINA', 'Cross-platform well-modulated matrices');
INSERT INTO box.boxer_teams (id, name, description) VALUES (37, 'ENLK', 'Synergistic analyzing local area network');
INSERT INTO box.boxer_teams (id, name, description) VALUES (38, 'USB^O', 'Innovative modular conglomeration');
INSERT INTO box.boxer_teams (id, name, description) VALUES (39, 'NODK', 'Object-based client-server project');
INSERT INTO box.boxer_teams (id, name, description) VALUES (40, 'HXL', 'Front-line disintermediate portal');
INSERT INTO box.boxer_teams (id, name, description) VALUES (41, 'ATNX', 'Inverse asynchronous time-frame');
INSERT INTO box.boxer_teams (id, name, description) VALUES (42, 'GAINM', 'Open-architected exuding definition');
INSERT INTO box.boxer_teams (id, name, description) VALUES (43, 'FORR', 'Inverse tertiary access');
INSERT INTO box.boxer_teams (id, name, description) VALUES (44, 'GPOR', 'Profit-focused modular secured line');
INSERT INTO box.boxer_teams (id, name, description) VALUES (45, 'ACIA', 'Object-based full-range definition');
INSERT INTO box.boxer_teams (id, name, description) VALUES (46, 'PTHN', 'Implemented radical process improvement');
INSERT INTO box.boxer_teams (id, name, description) VALUES (47, 'DYN', 'Persevering neutral monitoring');
INSERT INTO box.boxer_teams (id, name, description) VALUES (48, 'SRDX', 'Progressive executive internet solution');
INSERT INTO box.boxer_teams (id, name, description) VALUES (49, 'STZ.B', 'Polarised needs-based paradigm');
INSERT INTO box.boxer_teams (id, name, description) VALUES (50, 'VNO^L', 'Implemented responsive monitoring');
INSERT INTO box.boxer_teams (id, name, description) VALUES (51, 'DRAM', 'Diverse discrete array');
INSERT INTO box.boxer_teams (id, name, description) VALUES (52, 'ABG', 'Visionary maximized interface');
INSERT INTO box.boxer_teams (id, name, description) VALUES (53, 'VMO', 'Mandatory reciprocal capacity');
INSERT INTO box.boxer_teams (id, name, description) VALUES (54, 'ONS', 'Multi-channelled real-time forecast');
INSERT INTO box.boxer_teams (id, name, description) VALUES (55, 'WCC', 'Fully-configurable non-volatile hub');
INSERT INTO box.boxer_teams (id, name, description) VALUES (56, 'FFNW', 'Programmable client-server open system');
INSERT INTO box.boxer_teams (id, name, description) VALUES (57, 'DGLD', 'Quality-focused leading edge flexibility');
INSERT INTO box.boxer_teams (id, name, description) VALUES (58, 'IHG', 'Digitized holistic initiative');
INSERT INTO box.boxer_teams (id, name, description) VALUES (59, 'SHSP', 'Pre-emptive 5th generation info-mediaries');
INSERT INTO box.boxer_teams (id, name, description) VALUES (60, 'AOD', 'Enhanced multi-state solution');
INSERT INTO box.boxer_teams (id, name, description) VALUES (61, 'USAC', 'Expanded transitional knowledge base');
INSERT INTO box.boxer_teams (id, name, description) VALUES (62, 'CARZ', 'Cloned zero tolerance projection');
INSERT INTO box.boxer_teams (id, name, description) VALUES (63, 'ORIT', 'Distributed demand-driven structure');
INSERT INTO box.boxer_teams (id, name, description) VALUES (64, 'PNC^Q', 'Multi-channelled global budgetary management');
INSERT INTO box.boxer_teams (id, name, description) VALUES (65, 'TBPH', 'Re-engineered 4th generation encoding');
INSERT INTO box.boxer_teams (id, name, description) VALUES (66, 'MDGS', 'Automated cohesive time-frame');
INSERT INTO box.boxer_teams (id, name, description) VALUES (67, 'MHLD', 'Seamless high-level internet solution');
INSERT INTO box.boxer_teams (id, name, description) VALUES (68, 'FND', 'Universal non-volatile open architecture');
INSERT INTO box.boxer_teams (id, name, description) VALUES (69, 'TSEM', 'Synchronised bifurcated orchestration');
INSERT INTO box.boxer_teams (id, name, description) VALUES (70, 'CFO', 'Persistent fresh-thinking access');
INSERT INTO box.boxer_teams (id, name, description) VALUES (71, 'GRVY', 'Inverse value-added productivity');
INSERT INTO box.boxer_teams (id, name, description) VALUES (72, 'INCY', 'Exclusive dedicated moderator');
INSERT INTO box.boxer_teams (id, name, description) VALUES (73, 'CMC', 'Quality-focused transitional groupware');
INSERT INTO box.boxer_teams (id, name, description) VALUES (74, 'EVF', 'Universal non-volatile capability');
INSERT INTO box.boxer_teams (id, name, description) VALUES (75, 'RMGN', 'Function-based bifurcated architecture');
INSERT INTO box.boxer_teams (id, name, description) VALUES (76, 'DXTR', 'Front-line multi-state monitoring');
INSERT INTO box.boxer_teams (id, name, description) VALUES (77, 'AVP', 'Secured disintermediate extranet');
INSERT INTO box.boxer_teams (id, name, description) VALUES (78, 'MANT', 'Down-sized interactive strategy');
INSERT INTO box.boxer_teams (id, name, description) VALUES (79, 'VSTO', 'Multi-lateral radical benchmark');
INSERT INTO box.boxer_teams (id, name, description) VALUES (80, 'ETSY', 'Multi-layered regional ability');
INSERT INTO box.boxer_teams (id, name, description) VALUES (81, 'BYFC', 'Grass-roots 6th generation knowledge base');
INSERT INTO box.boxer_teams (id, name, description) VALUES (82, 'CXDC', 'De-engineered discrete benchmark');
INSERT INTO box.boxer_teams (id, name, description) VALUES (83, 'ARLP', 'Customizable even-keeled portal');
INSERT INTO box.boxer_teams (id, name, description) VALUES (84, 'ETP', 'Right-sized interactive secured line');
INSERT INTO box.boxer_teams (id, name, description) VALUES (85, 'HES^A', 'Reduced foreground synergy');
INSERT INTO box.boxer_teams (id, name, description) VALUES (86, 'SO', 'Mandatory even-keeled encoding');
INSERT INTO box.boxer_teams (id, name, description) VALUES (87, 'IBOC', 'Total user-facing ability');
INSERT INTO box.boxer_teams (id, name, description) VALUES (88, 'DSX^B', 'Inverse non-volatile application');
INSERT INTO box.boxer_teams (id, name, description) VALUES (89, 'GS^B', 'Optional analyzing array');
INSERT INTO box.boxer_teams (id, name, description) VALUES (90, 'AIZ', 'Reverse-engineered object-oriented moratorium');
INSERT INTO box.boxer_teams (id, name, description) VALUES (91, 'WFC', 'Upgradable context-sensitive collaboration');
INSERT INTO box.boxer_teams (id, name, description) VALUES (92, 'GRIF', 'Virtual neutral focus group');
INSERT INTO box.boxer_teams (id, name, description) VALUES (93, 'ENIC', 'Universal radical middleware');
INSERT INTO box.boxer_teams (id, name, description) VALUES (94, 'PCO', 'Progressive multimedia leverage');
INSERT INTO box.boxer_teams (id, name, description) VALUES (95, 'TCF^C', 'Re-contextualized systematic extranet');
INSERT INTO box.boxer_teams (id, name, description) VALUES (96, 'KRC^H', 'Organized methodical local area network');
INSERT INTO box.boxer_teams (id, name, description) VALUES (97, 'SYNA', 'Enhanced composite product');
INSERT INTO box.boxer_teams (id, name, description) VALUES (98, 'TENX', 'Visionary needs-based budgetary management');
INSERT INTO box.boxer_teams (id, name, description) VALUES (99, 'RAVN', 'Stand-alone transitional strategy');
INSERT INTO box.boxer_teams (id, name, description) VALUES (100, 'JAX', 'Upgradable 4th generation standardization');
INSERT INTO box.boxer_teams (id, name, description) VALUES (101, 'EL', 'Business-focused attitude-oriented throughput');
INSERT INTO box.boxer_teams (id, name, description) VALUES (102, 'CBO', 'Right-sized interactive application');
INSERT INTO box.boxer_teams (id, name, description) VALUES (103, 'EYEG', 'Function-based tertiary functionalities');
INSERT INTO box.boxer_teams (id, name, description) VALUES (104, 'CTSO', 'Multi-tiered national access');
INSERT INTO box.boxer_teams (id, name, description) VALUES (105, 'VNCE', 'Self-enabling analyzing software');
INSERT INTO box.boxer_teams (id, name, description) VALUES (106, 'CHKR', 'Up-sized bottom-line archive');
INSERT INTO box.boxer_teams (id, name, description) VALUES (107, 'TA', 'Stand-alone local access');
INSERT INTO box.boxer_teams (id, name, description) VALUES (108, 'FPXI', 'Customer-focused bifurcated collaboration');
INSERT INTO box.boxer_teams (id, name, description) VALUES (109, 'HOVNP', 'Upgradable asymmetric conglomeration');
INSERT INTO box.boxer_teams (id, name, description) VALUES (110, 'SYKE', 'Centralized grid-enabled framework');
INSERT INTO box.boxer_teams (id, name, description) VALUES (111, 'MSFT', 'Cloned tertiary emulation');
INSERT INTO box.boxer_teams (id, name, description) VALUES (112, 'DBD', 'Extended executive complexity');
INSERT INTO box.boxer_teams (id, name, description) VALUES (113, 'ABBV', 'Assimilated 24/7 monitoring');
INSERT INTO box.boxer_teams (id, name, description) VALUES (114, 'WLH', 'Monitored value-added portal');
INSERT INTO box.boxer_teams (id, name, description) VALUES (115, 'IHIT', 'Reduced eco-centric standardization');
INSERT INTO box.boxer_teams (id, name, description) VALUES (116, 'JAZZ', 'Customer-focused bifurcated projection');
INSERT INTO box.boxer_teams (id, name, description) VALUES (117, 'CATYW', 'Public-key clear-thinking capacity');
INSERT INTO box.boxer_teams (id, name, description) VALUES (118, 'CL', 'Progressive real-time forecast');
INSERT INTO box.boxer_teams (id, name, description) VALUES (119, 'ALT', 'Horizontal interactive hardware');
INSERT INTO box.boxer_teams (id, name, description) VALUES (120, 'WSTL', 'Operative uniform workforce');
INSERT INTO box.boxer_teams (id, name, description) VALUES (121, 'CAE', 'Grass-roots dynamic Graphical User Interface');
INSERT INTO box.boxer_teams (id, name, description) VALUES (122, 'ITIC', 'Exclusive foreground portal');
INSERT INTO box.boxer_teams (id, name, description) VALUES (123, 'SRCE', 'Organized non-volatile monitoring');
INSERT INTO box.boxer_teams (id, name, description) VALUES (124, 'GIGA', 'Realigned content-based standardization');
INSERT INTO box.boxer_teams (id, name, description) VALUES (125, 'GJP', 'Down-sized upward-trending attitude');
INSERT INTO box.boxer_teams (id, name, description) VALUES (126, 'MPWR', 'Universal encompassing infrastructure');
INSERT INTO box.boxer_teams (id, name, description) VALUES (127, 'TGS', 'Sharable incremental encoding');
INSERT INTO box.boxer_teams (id, name, description) VALUES (128, 'AEZS', 'Future-proofed tertiary standardization');
INSERT INTO box.boxer_teams (id, name, description) VALUES (129, 'ETY', 'Versatile 5th generation migration');
INSERT INTO box.boxer_teams (id, name, description) VALUES (130, 'NRG', 'Fully-configurable 24/7 methodology');
INSERT INTO box.boxer_teams (id, name, description) VALUES (131, 'SPEX', 'Synergistic executive parallelism');
INSERT INTO box.boxer_teams (id, name, description) VALUES (132, 'BEP', 'Balanced exuding local area network');
INSERT INTO box.boxer_teams (id, name, description) VALUES (133, 'IO', 'Balanced national info-mediaries');
INSERT INTO box.boxer_teams (id, name, description) VALUES (134, 'AGU', 'Seamless solution-oriented Graphical User Interface');
INSERT INTO box.boxer_teams (id, name, description) VALUES (135, 'HWKN', 'Focused intangible conglomeration');
INSERT INTO box.boxer_teams (id, name, description) VALUES (136, 'RM', 'Exclusive composite protocol');
INSERT INTO box.boxer_teams (id, name, description) VALUES (137, 'FAC', 'Self-enabling 4th generation framework');
INSERT INTO box.boxer_teams (id, name, description) VALUES (138, 'CFC^B', 'Fully-configurable motivating infrastructure');
INSERT INTO box.boxer_teams (id, name, description) VALUES (139, 'MULE', 'User-friendly mobile neural-net');
INSERT INTO box.boxer_teams (id, name, description) VALUES (140, 'SHLM', 'Inverse client-server standardization');
INSERT INTO box.boxer_teams (id, name, description) VALUES (141, 'MFD', 'Multi-lateral encompassing software');
INSERT INTO box.boxer_teams (id, name, description) VALUES (142, 'MTRX', 'Reduced reciprocal Graphical User Interface');
INSERT INTO box.boxer_teams (id, name, description) VALUES (143, 'TMUS', 'Compatible interactive artificial intelligence');
INSERT INTO box.boxer_teams (id, name, description) VALUES (144, 'HIO', 'Up-sized 5th generation migration');
INSERT INTO box.boxer_teams (id, name, description) VALUES (145, 'DFFN', 'Seamless leading edge concept');
INSERT INTO box.boxer_teams (id, name, description) VALUES (146, 'TMST', 'Switchable neutral focus group');
INSERT INTO box.boxer_teams (id, name, description) VALUES (147, 'WBA', 'Seamless non-volatile portal');
INSERT INTO box.boxer_teams (id, name, description) VALUES (148, 'GHL', 'Multi-tiered logistical product');
INSERT INTO box.boxer_teams (id, name, description) VALUES (149, 'OZRK', 'Mandatory asynchronous complexity');
INSERT INTO box.boxer_teams (id, name, description) VALUES (150, 'EPR', 'Vision-oriented needs-based alliance');
INSERT INTO box.boxer_teams (id, name, description) VALUES (151, 'PEY', 'Ergonomic solution-oriented initiative');
INSERT INTO box.boxer_teams (id, name, description) VALUES (152, 'TOO^A', 'Up-sized background extranet');
INSERT INTO box.boxer_teams (id, name, description) VALUES (153, 'TSRI', 'Persistent bifurcated budgetary management');
INSERT INTO box.boxer_teams (id, name, description) VALUES (154, 'ERIE', 'Profound actuating installation');
INSERT INTO box.boxer_teams (id, name, description) VALUES (155, 'GLPI', 'Quality-focused disintermediate service-desk');
INSERT INTO box.boxer_teams (id, name, description) VALUES (156, 'ONB', 'Ergonomic demand-driven secured line');
INSERT INTO box.boxer_teams (id, name, description) VALUES (157, 'NETS', 'Right-sized 24 hour adapter');
INSERT INTO box.boxer_teams (id, name, description) VALUES (158, 'TACO', 'Persevering hybrid neural-net');
INSERT INTO box.boxer_teams (id, name, description) VALUES (159, 'AIN', 'Up-sized tangible encoding');
INSERT INTO box.boxer_teams (id, name, description) VALUES (160, 'DAN', 'Vision-oriented composite contingency');
INSERT INTO box.boxer_teams (id, name, description) VALUES (161, 'HONE', 'Cross-group encompassing archive');
INSERT INTO box.boxer_teams (id, name, description) VALUES (162, 'SUN', 'Monitored mobile internet solution');
INSERT INTO box.boxer_teams (id, name, description) VALUES (163, 'AGZD', 'Multi-tiered actuating complexity');
INSERT INTO box.boxer_teams (id, name, description) VALUES (164, 'ACAD', 'Sharable stable concept');
INSERT INTO box.boxer_teams (id, name, description) VALUES (165, 'HMN', 'Advanced 5th generation framework');
INSERT INTO box.boxer_teams (id, name, description) VALUES (166, 'ENFC', 'Organized client-server workforce');
INSERT INTO box.boxer_teams (id, name, description) VALUES (167, 'HE^U', 'Virtual multi-tasking toolset');
INSERT INTO box.boxer_teams (id, name, description) VALUES (168, 'AZN', 'Open-source well-modulated product');
INSERT INTO box.boxer_teams (id, name, description) VALUES (169, 'ADAP', 'Quality-focused zero administration process improvement');
INSERT INTO box.boxer_teams (id, name, description) VALUES (170, 'QQQ', 'Balanced secondary functionalities');
INSERT INTO box.boxer_teams (id, name, description) VALUES (171, 'NP', 'Fundamental heuristic customer loyalty');
INSERT INTO box.boxer_teams (id, name, description) VALUES (172, 'GOOGL', 'Innovative leading edge support');
INSERT INTO box.boxer_teams (id, name, description) VALUES (173, 'SSFN', 'Ergonomic next generation interface');
INSERT INTO box.boxer_teams (id, name, description) VALUES (174, 'DSWL', 'Synchronised logistical knowledge base');
INSERT INTO box.boxer_teams (id, name, description) VALUES (175, 'RELL', 'Balanced discrete superstructure');
INSERT INTO box.boxer_teams (id, name, description) VALUES (176, 'RMD', 'Diverse tangible ability');
INSERT INTO box.boxer_teams (id, name, description) VALUES (177, 'FTRI', 'Re-contextualized reciprocal access');
INSERT INTO box.boxer_teams (id, name, description) VALUES (178, 'ASX', 'Quality-focused 4th generation flexibility');
INSERT INTO box.boxer_teams (id, name, description) VALUES (179, 'ACP', 'Focused motivating protocol');
INSERT INTO box.boxer_teams (id, name, description) VALUES (180, 'TUES', 'Balanced client-server moderator');
INSERT INTO box.boxer_teams (id, name, description) VALUES (181, 'VNDA', 'Compatible bifurcated utilisation');
INSERT INTO box.boxer_teams (id, name, description) VALUES (182, 'SEE', 'Front-line homogeneous contingency');
INSERT INTO box.boxer_teams (id, name, description) VALUES (183, 'HSY', 'Quality-focused motivating Graphical User Interface');
INSERT INTO box.boxer_teams (id, name, description) VALUES (184, 'NBN', 'Virtual logistical secured line');
INSERT INTO box.boxer_teams (id, name, description) VALUES (185, 'PSA^X', 'Mandatory multi-tasking architecture');
INSERT INTO box.boxer_teams (id, name, description) VALUES (186, 'TRN', 'Inverse 4th generation utilisation');
INSERT INTO box.boxer_teams (id, name, description) VALUES (187, 'GLOG', 'Front-line 5th generation leverage');
INSERT INTO box.boxer_teams (id, name, description) VALUES (188, 'MNR', 'Optimized didactic system engine');
INSERT INTO box.boxer_teams (id, name, description) VALUES (189, 'WFT', 'Visionary content-based neural-net');
INSERT INTO box.boxer_teams (id, name, description) VALUES (190, 'WPCS', 'Open-architected next generation solution');
INSERT INTO box.boxer_teams (id, name, description) VALUES (191, 'EVHC^', 'Ergonomic demand-driven moratorium');
INSERT INTO box.boxer_teams (id, name, description) VALUES (192, 'REVG', 'Visionary solution-oriented software');
INSERT INTO box.boxer_teams (id, name, description) VALUES (193, 'JBT', 'Focused tertiary conglomeration');
INSERT INTO box.boxer_teams (id, name, description) VALUES (194, 'PYZ', 'Team-oriented bandwidth-monitored open system');
INSERT INTO box.boxer_teams (id, name, description) VALUES (195, 'TTOO', 'Assimilated transitional secured line');
INSERT INTO box.boxer_teams (id, name, description) VALUES (196, 'TRQ', 'Devolved coherent database');
INSERT INTO box.boxer_teams (id, name, description) VALUES (197, 'GPIA', 'Adaptive fault-tolerant product');
INSERT INTO box.boxer_teams (id, name, description) VALUES (198, 'MB', 'Optional 5th generation superstructure');
INSERT INTO box.boxer_teams (id, name, description) VALUES (199, 'DWFI', 'Optimized needs-based access');
INSERT INTO box.boxer_teams (id, name, description) VALUES (200, 'WFT', 'Enterprise-wide value-added service-desk');

-- Set Next ID Value to MAX ID
SELECT setval('box.boxer_teams_id_seq', (SELECT MAX(id) FROM box.boxer_teams));